version: '3.9'

volumes:
  dotnet-minify-url:
    driver: local
    
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - dotnet-minify-url:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=2D1wIPm5wzvJNa8OXMYShLGN
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - dotnet-minify-url:/data/redis
    environment:
      - REDIS_PASSWORD=8mn1JpZ5oumuU2zTNwgK
    command:
      - redis-server
  
  minify-url:
    image: dotnet-minify-url
    container_name: dotnet-minify-url
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - mongodb
      - redis
    environment:
        - ASPNETCORE_ENVIRONMENT=Development